# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

### CONFIGURATION FOR MASTER BRANCH (Live Releases) ###
### This should be a Release build with symbols built for the nuget packages so they can be released to nuget.org ###
-
  branches:
    only:
      - master

  version: 0.1.0.{build}
  services:
  configuration: Release
  before_build:
  - ps: >-
      $versionToUse = $env:APPVEYOR_BUILD_VERSION

      .\tools\SetVersion.ps1 $versionToUse

      nuget restore
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal

### CONFIGURATION FOR RELEASE BRANCHES (Pre-release builds and deployments) ###
### This should be a Debug build but with symbols built for the nuget packages so they can be released as pre-release to nuget.org ###
-
  branches:
    only:
      - /release.*/
      - v([0-9]+)\.([0-9]+)\.([0-9]+)

  version: 0.1.0.{build}
  services:
  before_build:
  - ps: >-
      $versionToUse = $env:APPVEYOR_BUILD_VERSION

      .\tools\SetVersion.ps1 $versionToUse Beta

      nuget restore
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    verbosity: minimal

### CONFIGURATION FOR ALL OTHER BRANCHES (i.e. dev, feature and hot-fix) ###
### This should be a Debug build for internal testing only.  Artefacts should not be released into the 'wild' ###
-
  branches:
    except:
      - master
      - /release.*/
      - v([0-9]+)\.([0-9]+)\.([0-9]+)

  init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  version: 0.1.0.{build}
  services:
  before_build:
  - ps: >-
      $versionToUse = $env:APPVEYOR_BUILD_VERSION

      .\tools\SetVersion.ps1 $versionToUse Alpha

      nuget restore
  build:
    publish_nuget: true
    verbosity: minimal
  before_test:
  - ps: >-
      Import-Module .\tools\ControlIisExpress.psm1

      Start-IISExpress "C:\projects\Airy-ApplicationInsights-Owin\samples\Dematt.Airy.ApplicationInsights.Sample" 11156

  on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
